config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3}
  validates :description, presence: true, length: { maximum: 250}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  
  def new
    @todo = Todo.new
  end
  
  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:success] = "Todo was successfully created"
      redirect_to todo_path(@todo)
    else
      flash[:danger] ="Nope... Try it again"
      render 'new'
    end
  end
  
  def show
    
  end
  
  def edit
    
  end
  
  def update
    if @todo.update(todo_params)
      flash[:success] = "Todo was successfully Updated"
      redirect_to todo_path(@todo)
    else
      flash[:danger] = "That didn't work well! try again..."
      render 'edit'
    end
  end
  
  def index
    @todos = Todo.all
  end
  
  def destroy
     @todo.destroy
     flash[:success] = "Todo was deleted Successfully"
     redirect_to todos_path
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end
  
  def todo_params
    params.require(:todo).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">Created by Vincent Walker</footer>
</div>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
          </button>
          <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", root_path %></li>
          </ul>
         
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create a To Do", new_todo_path %></li>
            <li><%= link_to "To Do List", todos_path %></li>
          </ul> 
          </div>
        </nav>
      </div>
    
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodosOnAzure</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
      <%= render "layouts/flash" %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1 class="center">To Do (Using Azure)</h1>
</div>


<div class="well">
 <h4 class="text center home-text">Hello and welcome to the To Do app. This is just like a Chores list 
 you create at home where you can add a chore and delete it once its done Give it a try!!</h4>
</div>

<div class="container">
  
    <div>
      
      <%= link_to "Create a Todo", new_todo_path, class: "btn btn-default btn-lg fancy pull-right" %>
    
    </div>
  
</div>

app/views/todos/_errors.html.erb
<% if @todo.errors.any? %>
 <div class="row">
  <div class="col-md-8 col-md-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
    <h2 class="panel-title">
      <%= pluralize(@todo.errors.count, "error") %> prohibited this <%= @todo.class %> from being saved: <!-- Solution from recipes_test_rb 46 -->
     </h2>
      <div class="panel-body">
       <ul>
        <% @todo.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
      <% end %>
     </ul>
    </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/todos/_form.html.erb
<div class="row">
  <div class="col-md-12">
      <%= form_for(@todo, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :name %> 
          </div>
          <div class="col-md-8">
            <%= f.text_field :name, class: 'form-control', placeholder: "Name of todo", autofocus: true %>
          </div>
        </div>
      
      <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description %> 
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 5, class: 'form-control', placeholder: "Add todo description" %>
          </div>
        </div>
      
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary" %> 
          <%= link_to "Back to Index", todos_path, class: "btn btn-warning" %>
        </div>
      </div>
    
    <% end %>
  </div>
</div>

app/views/todos/edit.html.erb
<div class="row">
  <h2 class="text-center">Edit your To Do</h2>
</div>

<%= render "todos/errors" %>
<%= render "todos/form" %>

app/views/todos/index.html.erb
<div class="container">
  <div class="center">
  </div>
  <div class="row">
    <h1 class="text-center">To Do List</h1>
    <div class="col-md-8 col-md-offset-2">
        <p>
          <%= link_to "Create a To Do", new_todo_path, class: "btn btn-success" %>
        </p>
          <table class="table">
            <thead>
              <tr>
              <th>Name</th>
              <th>Description</th>
            </tr>
            </thead>
            <% @todos.each do |todo| %>
              <tbody>
                <tr class ="well profile-black-white-thin row <%= cycle('profile-black-white-thin-b', '') %>"> 
                  <td class="texties"><%= todo.name %></td>
                  <td class="texties"><%= todo.description %></td>
                  <td><%= link_to "Edit", edit_todo_path(todo), class: "btn btn-warning bttn" %></td>
                  <td><%= link_to "View", todo_path(todo), class: "btn btn-info bttn" %></td>
                  <td><%= link_to "Delete", todo_path(todo), method: :delete, data: {confirm: "Are you sure??"}, class: "btn btn-danger bttn" %></td>
                </tr>
              </tbody>
          <% end %>
        </table>
    </div>
  </div>

app/views/todos/new.html.erb
<div class="row">
  <h2 class="text-center new-page-text">Create an New To do</h2>
</div>

<% render "todos/errors" %>
<%= render "todos/form" %>

app/views/todos/show.html.erb
<%= render "todos/errors" %>

<div class="container">
  <div class="row">
    <h2 class="text-center">My To Do</h2>
    <div class="col-md-4 col-md-offset-4">
      <div class="well">
        <p><span class="descriptionText">Name:</span> <%= @todo.name %></p>
        <br />
        <p><span class="descriptionText">Description:</span> <%= @todo.description %></p>
        <p>
          <%= link_to "Edit This To Do", edit_todo_path(@todo), class: "btn btn-primary" %> 
          <%= link_to "Back to Index", todos_path, class: "btn btn-warning" %>
        </p>
      </div>
    </div>
  </div>
</div>